[UserKeys]
  [UserKeys.user111]
    Username = "user111"
    ApiKey = "key111"
    Channel = "my_channel"

  [UserKeys.user222]
    Username = "user222"
    ApiKey = "key222"
    Channel = "channel_222"
